[[redirects]]
from = "https://blog.gesteves.com/*"
to = "https://www.allencompassingtrip.com"
status = 301
force = true

[[redirects]]
from = "https://gesteves.netlify.com/*"
to = "https://www.allencompassingtrip.com"
status = 301
force = true

[[redirects]]
from = "https://photo.gesteves.com/*"
to = "https://www.allencompassingtrip.com/:splat"
status = 301
force = true

[[redirects]]
from = "/atom.xml"
to = "https://www.allencompassingtrip.com/feed"
status = 301
force = true

[[redirects]]
from = "https://www.gesteves.com/*"
to = "https://www.allencompassingtrip.com"
status = 301
force = true
